// Synthetic DOM only: dedicated API drafts/secrets and scoped review actions.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'..','panel.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
function extract(name){const start=script.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0,name);const first=script.indexOf('{',start);let depth=0,quote='';for(let i=first;i<script.length;i++){const c=script[i];if(quote){if(c==='\\')i++;else if(c===quote)quote='';continue;}if('\'"`'.includes(c)){quote=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return script.slice(start,i+1);}throw Error(name);}
class Element{constructor(tag='div'){this.tagName=tag;this.children=[];this.type='text';this.checked=false;this.value='';this.style={};this._text='';this.listeners={};this.classList={contains:()=>true};}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent||'').join('');}set innerHTML(v){throw Error('Untrusted content must not use innerHTML');}append(...rows){this.children.push(...rows);}replaceChildren(...rows){this.children=rows;this._text='';}addEventListener(key,callback){this.listeners[key]=callback;}focus(){this.focused=true;}}
const ids=new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1],new Element()]));
assert.equal(ids.size,[...html.matchAll(/\bid="([^"]+)"/g)].length,'DOM ids must remain unique');
for(const id of ['enabled','json','thinking','consent'])ids.get('moderation-api-'+id).type='checkbox';
for(const [id,min,max] of [['timeout',5,120],['output',32,4096],['context',1,40]]){Object.assign(ids.get('moderation-api-'+id),{type:'number',min,max});}
ids.get('moderation-review-state').value='pending';
const pending=[];let apiImpl=async()=>{};
const context=vm.createContext({document:{createElement:tag=>new Element(tag)},$:s=>ids.get(s.slice(1)),console,Number,Object,Map,JSON,Date,editingGroup:'10001',config:{moderation_api:{}},healthCount:value=>typeof value==='number'?String(value):'未记录',healthTime:value=>String(value??'时间未记录'),toast(){},api:(...args)=>apiImpl(...args)});
vm.runInContext("let moderationApiDraft=null,moderationApiSaved=null,moderationApiDirty=false,moderationApiRevision=0;let moderationReviewOffset=0,moderationReviewRequest=0,moderationReviewBusy=false,moderationReviewSignature='',moderationReviewTotal=0;const moderationReviewDrafts=new Map();",context);
for(const name of ['moderationApiDefaults','moderationApiFields'])vm.runInContext(script.match(new RegExp('^const '+name+'=[^\\n]+','m'))[0],context);
for(const name of ['publicModerationApi','initializeModerationApi','collectModerationApi','markModerationApiDraft','validateModerationApi','renderModerationApiStatus','renderModerationCollectionStatus','moderationReviewText','renderModerationReview','readModerationReview','requestModerationReview'])vm.runInContext(extract(name),context);
context.initializeModerationApi({api_key:'SERVER_SECRET_NEVER_DISPLAY',has_key:true});
assert.equal(ids.get('moderation-api-url').value,'');assert.equal(ids.get('moderation-api-enabled').checked,false);assert.equal(ids.get('moderation-api-consent').checked,false);assert.equal(ids.get('moderation-api-key').value,'');
assert(!JSON.stringify(context.publicModerationApi({api_key:'SERVER_SECRET_NEVER_DISPLAY'})).includes('SERVER_SECRET_NEVER_DISPLAY'));
ids.get('moderation-api-url').value='https://draft.example.invalid/v1';ids.get('moderation-api-model').value='draft-model';ids.get('moderation-api-key').value='UNSAVED_DEDICATED_SECRET';context.markModerationApiDraft();
const draft=JSON.stringify(context.collectModerationApi());context.renderModerationApiStatus({},true);context.renderModerationCollectionStatus({moderation_intake:{collecting_messages:3,collecting_turns:1,pending:2,expired:4,dropped:5}},true);
assert.equal(JSON.stringify(context.collectModerationApi()),draft);assert.equal(ids.get('moderation-api-key').value,'UNSAVED_DEDICATED_SECRET');assert(ids.get('moderation-api-status').textContent.includes('未配置专用接口：进入人工待审，不调用聊天模型'));
assert(ids.get('moderation-collection-progress').textContent.includes('原始收集中 3 条消息'));
for(const [id,value] of [['timeout',121],['output',31],['context',0]]){const el=ids.get('moderation-api-'+id),before=el.value;el.value=String(value);assert.throws(()=>context.validateModerationApi());el.value=before;}
const evil='<img src=x onerror=alert(1)>',item={id:'case-test',revision:1,state:'unknown',created_at:1,sources:[{id:'source-test',user_id:'10003',text:evil,received_at:1}],reason:evil,verdict:{evidence:evil},can_warn:false,warning_expired:true};
context.renderModerationReview({items:[item],total:1,counts:{pending:0,requested:0,unknown:1}},'10001');
const box=ids.get('moderation-review-items'),card=box.children[0];assert(card.textContent.includes(evil));const reason=card.children.find(c=>c.tagName==='input');reason.value='UNSAVED_CORRECTION';reason.oninput();const actions=card.children.at(-1);assert(actions.children[0].disabled,'Unknown must never allow repeat warning');assert(!actions.children[2].disabled,'Unknown may be corrected');
context.renderModerationReview({items:[{...item,revision:2}],total:1,counts:{unknown:1}},'10001');assert.equal(box.children[0].children.find(c=>c.tagName==='input').value,'UNSAVED_CORRECTION');
const normalCollect=extract('collect');assert(!normalCollect.includes('moderation-api-key'));assert(script.includes('delete value.api_key;value.moderation_api=publicModerationApi(value.moderation_api)'));
assert(!extract('renderStatus').includes('initializeModerationApi'));assert(script.includes("if(id==='url'||id==='model'){$('#moderation-api-consent').checked=false;$('#moderation-api-enabled').checked=false;}"));
assert(extract('render').includes('if(!moderationApiDraft)initializeModerationApi'));assert(extract('selectWorkspace').includes('resetModerationReview()'));
(async()=>{let resolve;apiImpl=()=>new Promise(r=>{resolve=r});const request=context.readModerationReview();context.editingGroup='10002';resolve({group_id:10001,items:[{...item,id:'STALE_CASE'}],total:1});await request;assert(!box.textContent.includes('STALE_CASE'));let calls=0;apiImpl=async()=>{calls++;};await context.requestModerationReview('10001',item,'warn','');assert.equal(calls,0,'Stale group actions must be rejected before request');console.log('Independent API defaults, secret/draft isolation, raw status, XSS-safe review and stale-group guards verified offline.');})().catch(error=>{console.error(error);process.exitCode=1;});
